export const students = [
  {
    id: 1,
    name: "Sardorbek",
    age: 17,
    address: "Samarqand",
    status: "Student",
    nikname: "King",
    univ: "Sejong",
    job: "Developer",
  },
  {
    id: 2,
    name: "Abror",
    age: 20,
    address: "Xorazim",
    status: "Student",
    nikname: "Alex",
    univ: "Sejong",
    job: "Developer",
  },
  {
    id: 3,
    name: "Shohijahon",
    age: 17,
    address: "Samarqand",
    status: "Student",
    nikname: "Shoxa",
    univ: "Sejong",
    job: "Developer",
  },
  {
    id: 4,
    name: "Nurdavlatbek",
    age: 17,
    address: "Anggren",
    status: "Student",
    nikname: "Davlatbek",
    univ: "Sejong",
    job: "Developer",
  },
];
